package org.bala.blog.bo;
// Generated Dec 9, 2013 12:20:31 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BlogComments generated by hbm2java
 */
@Entity
@Table(name="blog_comments")
public class BlogComments  implements java.io.Serializable {


     private int blogComid;
     private BlogUser blogUser;
     private BlogPost blogPost;
     private String cmdTittle;
     private String cmdSubject;

    public BlogComments() {
    }

	
    public BlogComments(int blogComid) {
        this.blogComid = blogComid;
    }
    public BlogComments(int blogComid, BlogUser blogUser, BlogPost blogPost, String cmdTittle, String cmdSubject) {
       this.blogComid = blogComid;
       this.blogUser = blogUser;
       this.blogPost = blogPost;
       this.cmdTittle = cmdTittle;
       this.cmdSubject = cmdSubject;
    }
   
     @Id 
    @GeneratedValue
    @Column(name="blog_comid", unique=true, nullable=false)
    public int getBlogComid() {
        return this.blogComid;
    }
    
    public void setBlogComid(int blogComid) {
        this.blogComid = blogComid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public BlogUser getBlogUser() {
        return this.blogUser;
    }
    
    public void setBlogUser(BlogUser blogUser) {
        this.blogUser = blogUser;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="blog_post_id")
    public BlogPost getBlogPost() {
        return this.blogPost;
    }
    
    public void setBlogPost(BlogPost blogPost) {
        this.blogPost = blogPost;
    }
    
    @Column(name="cmd_tittle", length=600)
    public String getCmdTittle() {
        return this.cmdTittle;
    }
    
    public void setCmdTittle(String cmdTittle) {
        this.cmdTittle = cmdTittle;
    }
    
    @Column(name="cmd_subject")
    public String getCmdSubject() {
        return this.cmdSubject;
    }
    
    public void setCmdSubject(String cmdSubject) {
        this.cmdSubject = cmdSubject;
    }




}


