package org.bala.blog.bo;
// Generated Dec 9, 2013 12:20:31 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlogUser generated by hbm2java
 */
@Entity
@Table(name="blog_user")
public class BlogUser  implements java.io.Serializable {


     private int userId;
     private String firstName;
     private String lastName;
     private String nickName;
     private String password;
     private Date createdDate;
     private Date updatedDate;
     private String emailid;
     private String url;
     private Set<BlogComments> blogCommentses = new HashSet<BlogComments>(0);
     private Set<BlogUserProfile> blogUserProfiles = new HashSet<BlogUserProfile>(0);

    public BlogUser() {
    }

	
    public BlogUser(int userId) {
        this.userId = userId;
    }
    public BlogUser(String firstName, String lastName, String nickName, String password) {
       
       this.firstName = firstName;
       this.lastName = lastName;
       this.nickName = nickName;
       this.password = password;
       
    }
   
     @Id 
    @GeneratedValue
    @Column(name="user_id", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="first_name", length=60)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="last_name", length=60)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="nick_name", length=60)
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    
    @Column(name="password", length=60)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_date", length=19)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Column(name="emailid", length=75)
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    
    @Column(name="url", length=100)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="blogUser")
    public Set<BlogComments> getBlogCommentses() {
        return this.blogCommentses;
    }
    
    public void setBlogCommentses(Set<BlogComments> blogCommentses) {
        this.blogCommentses = blogCommentses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="blogUser")
    public Set<BlogUserProfile> getBlogUserProfiles() {
        return this.blogUserProfiles;
    }
    
    public void setBlogUserProfiles(Set<BlogUserProfile> blogUserProfiles) {
        this.blogUserProfiles = blogUserProfiles;
    }




}


