package org.bala.blog.bo;
// Generated Dec 9, 2013 12:20:31 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlogTag generated by hbm2java
 */
@Entity
@Table(name="blog_tag")
public class BlogTag  implements java.io.Serializable {


     private int tagId;
     private String tagName;
     private Date createdDate;
     private Date updatedDate;

    public BlogTag() {
    }

	
    public BlogTag(int tagId) {
        this.tagId = tagId;
    }
    public BlogTag(int tagId, String tagName) {
       this.tagId = tagId;
       this.tagName = tagName;
    }
   
     @Id 
    @GeneratedValue
    @Column(name="tag_id", unique=true, nullable=false)
    public int getTagId() {
        return this.tagId;
    }
    
    public void setTagId(int tagId) {
        this.tagId = tagId;
    }
    
    @Column(name="tag_name", length=45)
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_date", length=19)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


