package org.bala.blog.bo;
// Generated Dec 9, 2013 12:20:31 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlogUserProfile generated by hbm2java
 */
@Entity
@Table(name = "blog_user_profile")
public class BlogUserProfile implements java.io.Serializable {

    private int userId;
    private BlogUser blogUser;
    private String userProfile;
    private Date createdDate;
    private Date updatedDate;

    public BlogUserProfile() {
    }

    public BlogUserProfile(int userId, BlogUser blogUser) {
        this.userId = userId;
        this.blogUser = blogUser;
    }

    public BlogUserProfile(String userProfile) {
        this.userProfile = userProfile;    
    }

    @Id
    @Column(name = "user_id", unique = true, nullable = false)
    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", unique = true, nullable = false, insertable = false, updatable = false)
    public BlogUser getBlogUser() {
        return this.blogUser;
    }

    public void setBlogUser(BlogUser blogUser) {
        this.blogUser = blogUser;
    }

    @Column(name = "user_profile")
    public String getUserProfile() {
        return this.userProfile;
    }

    public void setUserProfile(String userProfile) {
        this.userProfile = userProfile;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 19)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_date", length = 19)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}
